# @API_HOST = http://localhost:5223
@API_HOST = https://swiftlane-proxy-api-65310dfefa7e.herokuapp.com

### Proxy API Request
GET {{API_HOST}}/api/proxy?url=https://www.themealdb.com/api/json/v1/1/search.php?s=Peanut

### Health Check
GET {{API_HOST}}/health

###
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json
Authorization: Bearer Token

{
    "userId": 1,
    "id": 1,
    "title": "delectus aut autem",
    "completed": false
}

###
POST {{API_HOST}}/api/proxy?url=https://jsonplaceholder.typicode.com/posts
Content-Type: application/json
Authorization: Bearer Token

{
    "userId": 1,
    "id": 1,
    "title": "delectus aut autem",
    "completed": false
}


###
POST {{API_HOST}}/api/proxy?url=https://jsonplaceholder.typicode.com/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

{
    "userId": 1,
    "id": 1,
    "title": "delectus aut autem",
    "completed": false
}

###
GET  {{API_HOST}}/api/proxy?url=https://jsearch.p.rapidapi.com/estimated-salary?job_title=nodejs%20developer&location=new%20york&location_type=ANY&years_of_experience=ALL
X-Rapidapi-Key: ad0d72c24cmshaa4f5f8ea1b929dp149c70jsn211e4118758e
X-Rapidapi-Host: jsearch.p.rapidapi.com